default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000
  host: db
  username: postgres
  # password: Database created without password

development:
  <<: *default
  database: countries_app_development

test:
  <<: *default
  database: countries_app_test

production:
  <<: *default
  database: countries_app_production
  username: countries_app
  password: <%= ENV['COUNTRIES_APP_DATABASE_PASSWORD'] %>
